name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Install modules packages/common
      run: cd packages/common && npm install
    - name: Install modules packages/common-node
      run: cd packages/common-node && npm install
    - name: Build Rarities
      run: npm run build:rarities
    - name: Commit if changes
      run: |
        if [[ `git status --porcelain` ]]; then
          # Changes
          echo "Commiting Changes"

          # setup the username and email. 'GitHub Actions Bot' with no email
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
  
          # Stage the file, commit and push
          git add -A
          git commit -m "add build output"
          git push
        else
          # No changes
          echo "No Changes"
        fi
